name       : retroarch
version    : 1.2.2
release    : 1
source     :
    - https://github.com/libretro/RetroArch/archive/v1.2.2.tar.gz : 1113f75f6ddb790174b0f9e0fc82ff4875e8a4d39262428a6ba4a931a147b9af
license    : GPL-2.0
summary    : RetroArch is the official reference frontend for the libretro API.
description: Simple frontend for the libretro API. Stable version.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(xi)
    - pkgconfig(glu)
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
