name       : retroarch
version    : 1.3.4
release    : 6
source     :
    - https://github.com/libretro/RetroArch/archive/v1.3.4.tar.gz : a5733a0f4ad828afd00fa2a059deb6538939d46a2aefc4a566c30300a40efb1c
license    : GPL-2.0
component  : games.emulator
summary    : RetroArch is the official reference frontend for the libretro API.
description: Simple frontend for the libretro API. Stable version.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xv)
setup      : |
    ./configure --prefix=/usr \
                --enable-ffmpeg \
                --enable-jack \
                --enable-libusb \
                --enable-materialui \
                --enable-netplay \
                --enable-networking \
                --enable-opengl \
                --enable-pulse \
                --enable-sdl2 \
                --enable-wayland \
                --enable-x11
build      : |
    %make
install    : |
    %make_install
