name       : retroarch
version    : 1.3.6
release    : 10
source     :
    - http://stroblindustries.com/solus-tarballs/RetroArch-1.3.6.tar.gz : 1ac56b0f3bfba9ec3528244fe30a94bfcb3b074a5abcd4014ca37c13688ef2bb
license    : GPL-2.0
component  : games.emulator
summary    : RetroArch is the official reference frontend for the libretro API.
description: Simple frontend for the libretro API. Stable version.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xv)
    - git
    - libpth-devel
    - vulkan
setup      : |
    git submodule update --init
    ./configure --prefix=/usr \
        --enable-al \
        --enable-cheevos \
        --enable-ffmpeg \
        --enable-freetype \
        --enable-jack \
        --enable-libusb \
        --enable-materialui \
        --enable-netplay \
        --enable-networking \
        --enable-opengl \
        --enable-pulse \
        --enable-sdl2 \
        --enable-threads \
        --enable-v4l2 \
        --enable-vulkan \
        --enable-wayland \
        --enable-x11 \
        --enable-zlib
build      : |
    %make
install    : |
    %make_install
