name       : retroarch
version    : 1.10.3
release    : 67
source     :
    - https://github.com/libretro/RetroArch/archive/v1.10.3.tar.gz : 2af44294e55f5636262284d650cb5fff55c9070ac3a700d4fa55c1f152dcb3f2
    - git|https://github.com/libretro/retroarch-assets.git : f45dd1351e6bfb9f01e12bee8d358ad22a2bb8f9
license    : GPL-3.0-or-later
component  : games.emulator
summary    : RetroArch is the official reference frontend for the libretro API
description: |
    RetroArch is the reference frontend for the libretro API. Popular examples of implementations for this API includes videogame system emulators and game engines, but also more generalized 3D programs.
clang      : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(flac)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(libdecor-0)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - pkgconfig(openal)
    - pkgconfig(Qt5Gui)
    - pkgconfig(sdl2)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xv)
    - pkgconfig(xxf86vm)
    - mbedtls-devel
rundeps    :
    - libdecor
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-Defaults.patch

    ./configure --prefix=/usr \
        --enable-al \
        --enable-alsa \
        --enable-dbus \
        --enable-ffmpeg \
        --enable-freetype \
        --enable-jack \
        --enable-libusb \
        --enable-materialui \
        --enable-networking \
        --enable-opengl \
        --enable-ozone \
        --enable-pulse \
        --enable-qt \
        --enable-sse \
        --enable-sdl2 \
        --enable-threads \
        --enable-v4l2 \
        --enable-vulkan \
        --enable-wayland \
        --enable-x11 \
        --enable-zlib \
        --disable-builtinflac \
        --disable-builtinmbedtls \
        --disable-builtinzlib
build      : |
    %make
    %make -C gfx/video_filters
    %make -C libretro-common/audio/dsp_filters
install    : |
    %make_install

    # Default configurations are currently handled as source patches. Remove /etc/retroarch.cfg as a user may misleadingly 
    # modify it and have their changes overwritten on package updates
    rm -r $installdir/etc/

    install -D -m00644 libretro-common/audio/dsp_filters/*.{dsp,so} -t $installdir/%libdir%/retroarch/filters/audio/
    install -D -m00644 gfx/video_filters/*.{filt,so} -t $installdir/%libdir%/retroarch/filters/video/

    # Bundle menu assets. This allows users to use Retroarch immediately without having to use the update tool
    install -dm 755 $installdir/usr/share/retroarch/assets
    cp -dr --preserve=mode,timestamps $sources/retroarch-assets.git/glui $installdir/usr/share/retroarch/assets/
    cp -dr --preserve=mode,timestamps $sources/retroarch-assets.git/ozone $installdir/usr/share/retroarch/assets/
    cp -dr --preserve=mode,timestamps $sources/retroarch-assets.git/xmb $installdir/usr/share/retroarch/assets/
