name       : retroarch
version    : 1.3.4
release    : 4
source     :
    - https://github.com/libretro/RetroArch/archive/v1.3.4.tar.gz : a5733a0f4ad828afd00fa2a059deb6538939d46a2aefc4a566c30300a40efb1c
license    : GPL-2.0
summary    : RetroArch is the official reference frontend for the libretro API.
description: Simple frontend for the libretro API. Stable version.
component  : desktop.games
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(xi)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(libavcodec)
    - pkgconfig(xinerama)
    - pkgconfig(xv)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - jack-audio-connection-kit-devel
setup      : |
    ./configure --prefix=/usr \
                --enable-sdl2 \
                --enable-libusb \
                --enable-ffmpeg \
                --enable-networking \
                --enable-netplay \
                --enable-opengl \
                --enable-x11 \
                --enable-wayland \
                --enable-jack \
                --enable-pulse
build      : |
    %make
install    : |
    %make_install
